resources:
  - ../../base

secretGenerator:
  - name: influxdb-secret
    envs:
      - influxdb-secret.env

generatorOptions:
  disableNameSuffixHash: true

patches:
  - target:
      kind: Service
      name: hub-service
    patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer
