apiVersion: v1
kind: ServiceAccount
metadata:
  name: hub-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hub-scale-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hub-scale-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hub-scale-role
subjects:
  - kind: ServiceAccount
    name: hub-sa
