apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secret
type: Opaque
stringData:
  INFLUXDB_ADMIN_USER: CHANGE_ME
  INFLUXDB_ADMIN_PASSWORD: CHANGE_ME
  INFLUXDB_ADMIN_TOKEN: CHANGE_ME
  INFLUXDB_ORG: CHANGE_ME
  INFLUXDB_BUCKET: CHANGE_ME
