resources:
  - ../../base

secretGenerator:
  - name: hub-tls
    files:
      - tls/tls.crt
      - tls/tls.key
    type: kubernetes.io/tls
  - name: influxdb-secret
    envs:
      - influxdb-secret.env

generatorOptions:
  disableNameSuffixHash: true

patches:
  - target:
      kind: Service
      name: hub-service
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 30443
  - target:
      kind: Deployment
      name: resource-hub
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: resource-hub
      spec:
        template:
          spec:
            containers:
              - name: hub
                env:
                  - name: OTEL_EXPORTER_OTLP_INSECURE
                    value: "true"
  - target:
      kind: Deployment
      name: trace-svc
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: trace-svc
      spec:
        template:
          spec:
            containers:
              - name: trace-svc
                env:
                  - name: OTEL_EXPORTER_OTLP_INSECURE
                    value: "true"
